---
# The name of your system
title: "WhistleToChords"
subtitle: "Built with Euterpe"

# Set the correct flags based on the type of your music interaction algorithm
interactionMode: 
  noteMode: true
  audioMode: true

noteModeSettings:
  eventBased:
    # If eventBased.status: true, then the worker's processNoteEvent() hook is active
    # for instant processing of each user's MIDI event.
    status: false
  gridBased:
    # If gridBased.status: true, then the worker's processClockEvent() hook is active
    # for processing raw and quantized MIDI events buffers at every "clock-tick"
    status: true
    # Choose what information you want Euterpe to provide to your algorithm (Worker)
    # when calling the processClockEvent() hook, at every clock-tick (or grid slot)
    eventBuffer: false # A buffer with all the MIDI events played by the user since the last tick (grid slot).
    quantizedEvents: false # The time-quantized (or grid-aligned) MIDI events that correspond to the current tick (grid slot).
    # Set the polyphony that your music algorithm supports. Euterpe limits the user's input polyphony
    # so that you don't have to do it. Currently, it only applies to the quantizedEvents (gridBased mode)
    polyphony:
      input: 1
    # Optional feature to better align the user's input with the metronome
    # It drastically improves the displayed score due to better the better alignment.
    # For details, check our paper (section 3.4.1)
    # Use only when necessary though, as it might introduce clock/tempo instabilities.
    delayedExecution: false

audioModeSettings:
  windowSize: 8192
  hopSize: 8192

# The settings for the clockBased operation.
# These are taken into account not only if "noteMode: true"
clockSettings:
  # If autoStart is true, then the clock starts just after 
  # the intro screen is shown without the need for the user
  # to hit the play button (or the space bar)
  autoStart: true
  # You need to set the clock's tick duration.
  # This can happen either by: 

  # ---- OPTION 1: setting timeSignature, ticksPerBeat and BPM
  ticksPerBeat: 4 # use that for 16th-note grid on 4/4
  timeSignature:
    numerator: 4
    denominator: 4
  # This is just the default value. The user can later change it
  # from the settings menu (effectively changing the clock's period)
  defaultBPM: 60

  # ---- OPTION 2: 
  # Set the clockPeriod explicitly (milliseconds >100)
  # if not null, then the ticksPerBeat, timeSignature and defaultBPM are ignored
  # Use only if your music interaction algorithm
  # operates on a "free-time" mode (no BPM or timeSignature)
  clockPeriod: null
  
# Agent related settings.
agentSettings:
  # For Agents that require warmup (such as neural networks)
  warmupRounds: 2

# Choose the text to be displayed in the splash screen animation
introModal: false
introModalContent:
  - "Hi! This is a basic agent to demonstrate the audio-input capabilities of Euterpe"
  - "It uses Meyda to estimate rms, chroma features and extract pitch from the audio input"
  - "and then generates chords based on a simple rule based algorithm "
custom:
  useTriggerRelease: true