gui:
  score: 
    status: false
  textBox:
    status: false
    title: "TextBox Title"
  pianoRoll:
    status: true
    human: false
    agent: true
  keyboard:
    status: true # not used (always true)
    # set the visible octaves. Max range [0,8]
    octaveStart: 1
    octaveEnd: 7
  chromaChart:
    status: true
  audioMeter: 
    status: true
  
  settingsModal:
    sliders:
      - id: 1 
        label: "Temperature"
        value: 25
        min: 0
        max: 100
  monitor:
    status: true
    title: "Monitor"
    structure:
      - label: "Debugging"
        parameters:
          # The 'id' for each parameter must be unique and is used
          # in the hooks for adding new values for monitoring
          # The 'label' is the parameter name that appears in the GUI.
          # The 'interval' is the refresh rate of the parameter in ms.
          # The 'graph' flag allows you to visualize the value as a time grpah.
          # The 'min' and 'max' indicate the expected range of the parameter.
          - id: 0
            label: "inference" 
            interval: 50
            graph: true
            min: 0
            max: 40



